//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateEntities : DbContext
    {
        public RealEstateEntities()
            : base("name=RealEstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Account> tbl_Account { get; set; }
        public virtual DbSet<tbl_CategoryOfFurniture> tbl_CategoryOfFurniture { get; set; }
        public virtual DbSet<tbl_CategoryOfImagesRental> tbl_CategoryOfImagesRental { get; set; }
        public virtual DbSet<tbl_CategoryOfRoom> tbl_CategoryOfRoom { get; set; }
        public virtual DbSet<tbl_CategoryOfSellImages> tbl_CategoryOfSellImages { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_District> tbl_District { get; set; }
        public virtual DbSet<tbl_FurnitureRentalDetail> tbl_FurnitureRentalDetail { get; set; }
        public virtual DbSet<tbl_Images> tbl_Images { get; set; }
        public virtual DbSet<tbl_Owner> tbl_Owner { get; set; }
        public virtual DbSet<tbl_Position> tbl_Position { get; set; }
        public virtual DbSet<tbl_RealEstateRental> tbl_RealEstateRental { get; set; }
        public virtual DbSet<tbl_RoomLeaseDetail> tbl_RoomLeaseDetail { get; set; }
        public virtual DbSet<tbl_RoomSellDetail> tbl_RoomSellDetail { get; set; }
        public virtual DbSet<tbl_SellFurnitureDetail> tbl_SellFurnitureDetail { get; set; }
        public virtual DbSet<tbl_SellingRealEstate> tbl_SellingRealEstate { get; set; }
        public virtual DbSet<tbl_Ward> tbl_Ward { get; set; }
    }
}
