//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CategoryOfFurniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CategoryOfFurniture()
        {
            this.tbl_FurnitureRentalDetail = new HashSet<tbl_FurnitureRentalDetail>();
            this.tbl_SellFurnitureDetail = new HashSet<tbl_SellFurnitureDetail>();
        }
    
        public int ID_CategoryOfFurniture { get; set; }
        public string Name { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FurnitureRentalDetail> tbl_FurnitureRentalDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SellFurnitureDetail> tbl_SellFurnitureDetail { get; set; }
    }
}
