//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SellingRealEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SellingRealEstate()
        {
            this.tbl_CategoryOfSellImages = new HashSet<tbl_CategoryOfSellImages>();
            this.tbl_RoomSellDetail = new HashSet<tbl_RoomSellDetail>();
            this.tbl_SellFurnitureDetail = new HashSet<tbl_SellFurnitureDetail>();
        }
    
        public int ID_SellingRealEstate { get; set; }
        public string SellingRealEstate_Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Ward { get; set; }
        public Nullable<int> Acreage { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Unit { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Image { get; set; }
        public string Describe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CategoryOfSellImages> tbl_CategoryOfSellImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomSellDetail> tbl_RoomSellDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SellFurnitureDetail> tbl_SellFurnitureDetail { get; set; }
        public virtual tbl_Ward tbl_Ward { get; set; }
    }
}
