//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RealEstateRental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_RealEstateRental()
        {
            this.tbl_CategoryOfImagesRental = new HashSet<tbl_CategoryOfImagesRental>();
            this.tbl_FurnitureRentalDetail = new HashSet<tbl_FurnitureRentalDetail>();
            this.tbl_RoomLeaseDetail = new HashSet<tbl_RoomLeaseDetail>();
        }
    
        public int ID_RealEstateRental { get; set; }
        public string RealEstateRental_Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Ward { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Acreage { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Unit { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Image { get; set; }
        public string Describe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CategoryOfImagesRental> tbl_CategoryOfImagesRental { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FurnitureRentalDetail> tbl_FurnitureRentalDetail { get; set; }
        public virtual tbl_Ward tbl_Ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomLeaseDetail> tbl_RoomLeaseDetail { get; set; }
    }
}
