//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Owner
    {
        public int ID_Owner { get; set; }
        public string Owner_Name { get; set; }
        public Nullable<byte> SEX { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Company_Name { get; set; }
        public string Describe { get; set; }
        public string Owner_Account { get; set; }
        public string Owner_Password { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
