//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CategoryOfRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CategoryOfRoom()
        {
            this.tbl_RoomLeaseDetail = new HashSet<tbl_RoomLeaseDetail>();
            this.tbl_RoomSellDetail = new HashSet<tbl_RoomSellDetail>();
        }
    
        public int ID_CategoryOfRoom { get; set; }
        public string CategoryOfRoomName { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomLeaseDetail> tbl_RoomLeaseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoomSellDetail> tbl_RoomSellDetail { get; set; }
    }
}
